name: Deployment Pipeline Lint & Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check linting
        run: npm run eslint

      - name: Installing Playwright Browsers
        run: npx playwright install --with-deps

      - name: Jest Test
        run: npm run test

      - name: Playwright Test
        run: npm run test-pr
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment on Render
        if: ${{ github.event_name == "push" }}
        uses: sws2apps/render-deployment@main
        with: 
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
          multipleDeployment: false